version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres_eternal_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
    - 'POSTGRES_DB=eternal_db'
    - 'POSTGRES_USER=rest_server'
    - 'POSTGRES_PASSWORD=123456'
    - 'PGDATA=/var/lib/postgresql/data/pgdata'

  app:
    container_name: eternal_rest
    network_mode: bridge
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
        - 'postgres:rest-database'